// examples/react-cdn/src/App.js
import React from 'react';
import './App.css';

const dbr = window.dbr;
dbr.licenseKey = 'LICENSE-KEY';
const scanner = new dbr.Scanner({
    onFrameRead: results => { console.log(results); }, // eslint-disable-line
    onNewCodeRead: (txt, result) => { alert(txt); } // eslint-disable-line
});

class App extends React.Component {
  openScanner() {
    scanner.open();
  };
  render() {
    return ( 
      <div className="App">
        <button onClick={() => { this.openScanner() }}>open scanner</button>
      </div> 
    );
  };
}

export default App;

// examples/vue-cdn/src/App.vue
<template>
  <div id="app">
    <button v-on:click="openScanner">open scanner</button>
  </div>
</template>

<script>
import dbr from 'dbr'

dbr.licenseKey = 'LICENSE-KEY';
const scanner = new dbr.Scanner({
    onFrameRead: results => { console.log(results); }, // eslint-disable-line
    onNewCodeRead: (txt, result) => { alert(txt); } // eslint-disable-line
});

export default {
  name: 'app',
  methods: {
    openScanner(){
      scanner.open();
    }
  }
}
</script>
