// example/web/react/src/App.js
import React from 'react';
import './App.css';

const Dynamsoft = window.Dynamsoft;
class App extends React.Component {
  showScanner() {
    let scanner = null;
    Dynamsoft.BarcodeScanner.createInstance({
        onFrameRead: results => {console.log(results);},
        onUnduplicatedRead: (txt, result) => {alert(txt);}
    }).then(s => {
        scanner = s;
        scanner.show().catch(ex=>{
            console.log(ex);
            alert(ex.message || ex);
            scanner.hide();
        });
    });
  };
  render() {
    return ( 
      <div className="App">
        <button onClick={() => { this.showScanner() }}>show scanner</button>
      </div> 
    );
  };
}

export default App;

// example/web/vue/src/App.vue
<template>
  <div id="app">
    <button v-on:click="showScanner">show scanner</button>
  </div>
</template>

<script>
import Dynamsoft from 'Dynamsoft'

export default {
  name: 'app',
  methods: {
    showScanner(){
      let scanner = null;
      Dynamsoft.BarcodeScanner.createInstance({
          onFrameRead: results => {window.console.log(results);},
          onUnduplicatedRead: (txt) => {alert(txt);}
      }).then(s => {
          scanner = s;
          scanner.show().catch(ex=>{
              window.console.log(ex);
              window.alert(ex.message || ex);
              scanner.hide();
          });
      });
    }
  }
}
</script>
