// examples/angular-cdn/src/app/app.component.ts
import { Component } from '@angular/core';

let dbr = (window as any).dbr;
dbr.licenseKey = 'LICENSE-KEY';
let scanner = new dbr.Scanner({
    onFrameRead: results => {console.log(results);}, // eslint-disable-line
    onNewCodeRead: (txt, result) => {alert(txt);} // eslint-disable-line
});

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'dbr-cdn-angular-default';

  openScanner() {
    scanner.open();
  }
}

<button (click)="openScanner()">open scanner</button>

// examples/react-cdn/src/App.js
import React from 'react';
import './App.css';

const dbr = window.dbr;
dbr.licenseKey = 'LICENSE-KEY';
const scanner = new dbr.Scanner({
    onFrameRead: results => { console.log(results); }, // eslint-disable-line
    onNewCodeRead: (txt, result) => { alert(txt); } // eslint-disable-line
});

class App extends React.Component {
  openScanner() {
    scanner.open();
  };
  render() {
    return ( 
      <div className="App">
        <button onClick={() => { this.openScanner() }}>open scanner</button>
      </div> 
    );
  };
}

export default App;
