// example/web/vue/src/components/HelloWorld.vue
<template>
  <div>
    <h1>{{ title }}</h1>
    
    <div v-if="!bShowScanner">
      Choose image(s) to decode:
      <input v-on:change="onIptChange" type="file" multiple accept="image/png,image/jpeg,image/bmp,image/gif">
      <br><br>
      <button v-on:click="showScanner">show scanner</button>
    </div>

    <div v-if="bShowScanner">
      <button v-on:click="hideScanner">hide scanner</button>
      <BarcodeScanner v-on:appendMessage="appendMessage"></BarcodeScanner>
    </div>

    <div class="div-message">
      <p v-for="(message, index) of messages" v-bind:key="messageKeyBase + index">
        {{ message }}
      </p>
    </div>
  </div>
</template>

<script>
import Dynamsoft from "../Dynamsoft";
import BarcodeScanner from "./BarcodeScanner";

export default {
  props: {
    title: String
  },
  data() { 
    return {
      reader: null,
      messageKeyBase: 0,
      messages: [],
      bShowScanner: false
    };
  },
  components: {
    BarcodeScanner
  },
  beforeDestroy(){
    if(this.reader){
      this.reader.destroy();
    }
  },
  methods: {
    appendMessage(str){
      this.messages.push(str);
      if(this.messages.length > 500){
        ++this.messageKeyBase;
        this.messages.splice(0, 1);
      }
    },
    async onIptChange(event) {
      try{
        this.appendMessage("======== start read... ========");
        let reader = this.reader = this.reader || await Dynamsoft.BarcodeReader.createInstance();
        let input = event.target;
        let files = input.files;
        for(let i = 0; i < files.length; ++i){
          let file = files[i];
          this.appendMessage(file.name + ':')
          let results = await reader.decode(file);
          for(let result of results){
            this.appendMessage(result.barcodeText);
          }
        }
        input.value = "";
        this.appendMessage("======== finish read ========");
      }catch(ex){
        this.appendMessage(ex.message);
        console.error(ex);
      }
    },
    showScanner(){
      this.bShowScanner = true;
    },
    hideScanner(){
      this.bShowScanner = false;
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.div-message{
  max-height: 400px;
  overflow-y: auto;
}
</style>

// example/web/react/src/components/HelloWorld.js
import Dynamsoft from "../Dynamsoft";
import React from 'react';
import BarcodeScanner from './BarcodeScanner';

class HelloWorld extends React.Component {
    constructor(props){
        super(props);
        this.reader = null;
        this.state = {
            messageKeyBase: 0,
            messages: [],
            bShowScanner: false
        };
    }
    componentWillUnmount(){
        if(this.reader){
            this.reader.destroy();
        }
    }
    render() {
        return (
            <div>
                <h1>{ this.props.title }</h1>

                { !this.state.bShowScanner ? (
                    <div>
                        Choose image(s) to decode:
                        <input onChange={this.onIptChange} type="file" multiple accept="image/png,image/jpeg,image/bmp,image/gif" />
                        <br/><br/>
                        <button onClick={this.showScanner}>show scanner</button>
                    </div>
                ) : (
                    <div>
                        <button onClick={this.hideScanner}>hide scanner</button>
                        <BarcodeScanner appendMessage={this.appendMessage}></BarcodeScanner>
                    </div>
                ) }
            
                <div className="div-message" style={style.div_message}>
                    { this.state.messages.map((message, index) => 
                        <p key={ this.state.messageKeyBase + index }>
                            { message }
                        </p>
                    ) }
                </div>
            </div>
        );
    }
    appendMessage = str => {
        this.setState(state=>{
            state.messages.push(str);
            if(state.messages.length > 500){
                ++state.messageKeyBase;
                state.messages.splice(0, 1);
            }
            return state;
        });
    }
    onIptChange = event=>{
        // React can't get event.target in async func by default.
        // Thus get event.target in sync part.
        let input = event.target;

        (async ()=>{
            try{
                this.appendMessage("======== start read... ========");
                let reader = this.reader = this.reader || await Dynamsoft.BarcodeReader.createInstance();
                let files = input.files;
                for(let i = 0; i < files.length; ++i){
                let file = files[i];
                this.appendMessage(file.name + ':')
                let results = await reader.decode(file);
                for(let result of results){
                    this.appendMessage(result.barcodeText);
                }
                }
                input.value = "";
                this.appendMessage("======== finish read ========");
            }catch(ex){
                this.appendMessage(ex.message);
                console.error(ex);
            }
        })();
    }
    showScanner = ()=>{
        this.setState({
            bShowScanner: true
        });
    }
    hideScanner = ()=>{
        this.setState({
            bShowScanner: false
        });
    }
}

const style = {
    div_message: {
        maxHeight: "400px",
        overflowY: "auto"
    }
}

export default HelloWorld;
