// example/web/vue/src/components/HelloWorld.vue
<template>
  <div>
    <h1>{{ title }}</h1>
    
    <div v-if="!bShowScanner">
      Choose image(s) to decode:
      <input v-on:change="onIptChange" type="file" multiple accept="image/png,image/jpeg,image/bmp,image/gif">
      <br><br>
      <button v-on:click="showScanner">show scanner</button>
    </div>

    <div v-if="bShowScanner">
      <button v-on:click="hideScanner">hide scanner</button>
      <BarcodeScanner v-on:appendMessage="appendMessage"></BarcodeScanner>
    </div>

    <div class="div-message">
      <p v-for="(message, index) of messages" v-bind:key="messageKeyBase + index">
        {{ message }}
      </p>
    </div>
  </div>
</template>

<script>
import Dynamsoft from "../Dynamsoft";
import BarcodeScanner from "./BarcodeScanner";

export default {
  props: {
    title: String
  },
  data() { 
    return {
      reader: null,
      messageKeyBase: 0,
      messages: [],
      bShowScanner: false
    };
  },
  components: {
    BarcodeScanner
  },
  beforeDestroy(){
    if(this.reader){
      this.reader.destroy();
    }
  },
  methods: {
    appendMessage(str){
      this.messages.push(str);
      if(this.messages.length > 500){
        ++this.messageKeyBase;
        this.messages.splice(0, 1);
      }
    },
    async onIptChange(event) {
      try{
        this.appendMessage("======== start read... ========");
        let reader = this.reader = this.reader || await Dynamsoft.BarcodeReader.createInstance();
        let input = event.target;
        let files = input.files;
        for(let i = 0; i < files.length; ++i){
          let file = files[i];
          this.appendMessage(file.name + ':')
          let results = await reader.decode(file);
          for(let result of results){
            this.appendMessage(result.barcodeText);
          }
        }
        input.value = "";
        this.appendMessage("======== finish read ========");
      }catch(ex){
        this.appendMessage(ex.message);
        console.error(ex);
      }
    },
    showScanner(){
      this.bShowScanner = true;
    },
    hideScanner(){
      this.bShowScanner = false;
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.div-message{
  max-height: 400px;
  overflow-y: auto;
}
</style>

// example/web/angular/src/app/hello-world/hello-world.component.ts
import { Component, OnDestroy, Input } from '@angular/core';
import Dynamsoft from "../Dynamsoft";

@Component({
  selector: 'app-hello-world',
  templateUrl: './hello-world.component.html',
  styleUrls: ['./hello-world.component.scss']
})
export class HelloWorldComponent implements OnDestroy {

  @Input() title;
  
  reader = null;
  messageKeyBase = 0;
  messages = [];
  bShowScanner = false;

  constructor() { }

  ngOnDestroy(){
    if(this.reader){
      this.reader.destroy();
    }
  }

  appendMessage(str){
    this.messages.push(str);
    if(this.messages.length > 500){
      ++this.messageKeyBase;
      this.messages.splice(0, 1);
    }
  }
  async onIptChange(event) {
    try{
      this.appendMessage("======== start read... ========");
      let reader = this.reader = this.reader || await Dynamsoft.BarcodeReader.createInstance();
      let input = event.target;
      let files = input.files;
      for(let i = 0; i < files.length; ++i){
        let file = files[i];
        this.appendMessage(file.name + ':')
        let results = await reader.decode(file);
        for(let result of results){
          this.appendMessage(result.barcodeText);
        }
      }
      input.value = "";
      this.appendMessage("======== finish read ========");
    }catch(ex){
      this.appendMessage(ex.message);
      console.error(ex);
    }
  }
  showScanner(){
    this.bShowScanner = true;
  }
  hideScanner(){
    this.bShowScanner = false;
  }

}


<h1>{{ title }}</h1>

<div *ngIf="!bShowScanner">
    Choose image(s) to decode:
    <input (change)="onIptChange($event)" type="file" multiple accept="image/png,image/jpeg,image/bmp,image/gif">
    <br><br>
    <button (click)="showScanner()">show scanner</button>
</div>

<div *ngIf="bShowScanner">
    <button (click)="hideScanner()">hide scanner</button>
    <app-barcode-scanner (appendMessage)="appendMessage($event)"></app-barcode-scanner>
</div>

<div class="div-message">
    <p *ngFor="let message of messages">
    {{ message }}
    </p>
</div>
